### PR TITLE
fix: Refactoring the storage of the access key to the keychain

### LINKED ISSUE #435: Error Using `near login` with NEAR CLI: Failed to Save Access Key to Keychain on WSL Linux Environment
**Description:**

I encountered an issue while trying to use `near login` to deploy a Rust contract for the NEAR auction tutorial on a Linux environment (running in Windows, WSL). The CLI fails to save the access key to the keychain due to a missing `org.freedesktop.secrets` service.

### **Steps to Reproduce:**
1. Run the command:  
   ```bash
   near login
   ```
2. Follow the provided URL to authenticate via the browser.
3. Return to the CLI and enter the account ID as prompted.
4. Select the option to save the access key in the keychain.
5. Encounter the following error:

### **Error Message:**
```
Failed to open a temporary file to store a cli command
Error:
   0: Failed to save the access key <ed25519:...> to the keychain
   1: Failed to save password to keychain. You may need to install the secure keychain package by following this instruction: https://github.com/jaraco/keyring#using-keyring-on-headless-linux-systems
   2: Platform secure storage failure: DBus error: The name org.freedesktop.secrets was not provided by any .service files
   3: DBus error: The name org.freedesktop.secrets was not provided by any .service files
   4: The name org.freedesktop.secrets was not provided by any .service files

Location:
   src/common.rs:1349
```

### **Expected Behavior:**
The CLI should successfully save the access key to the selected keychain without errors.

### **Actual Behavior:**
The CLI fails to save the access key, indicating a missing `org.freedesktop.secrets` service.
image

### **Environment:**
- NEAR CLI version: near-cli-rs 0.17.0
- Operating System: windows 11

### PR DESCRIPTION
**Pull request by FroVolod**
Resolves #435 

Screenshot 2025-01-22 at 20 47 36

### CODE REVIEW

File: src/common.rs [hunk 1]
```diff
@@ -1348,7 +1383,8 @@ pub fn save_access_key_to_keychain(
         .set_password(key_pair_properties_buf)
         .wrap_err("Failed to save password to keychain. You may need to install the secure keychain package by following this instruction: https://github.com/jaraco/keyring#using-keyring-on-headless-linux-systems")?;
 
-    Ok("The data for the access key is saved in the keychain".to_string())
+    // Ok("The data for the access key is saved in the keychain".to_string())
+    color_eyre::eyre::bail!(keyring::error::Error::NoEntry)
```
Comment (frol) [inline src/common.rs:1387]: I believe it was used for testing only. Please, revert the change

**Comment by frol** [comment]
@race-of-sloths score 3

**Comment by race-of-sloths** [comment]
@FroVolod Thank you for your contribution! Your pull request is now a part of the [Race of Sloths](https://race-of-sloths.com)!
Weekly streak is on the road, smart strategy! Secure your streak with another PR!

[<picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://race-of-sloths.com/images/bot-banner-dark.svg">
    <source media="(prefers-color-scheme: light)" srcset="https://race-of-sloths.com/images/bot-banner-light.svg">
    Shows inviting banner with latest news.
</picture>](https://race-of-sloths.com/latest-news)

[<picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://badge.race-of-sloths.com/FroVolod?type=bot&pr=near/near-cli-rs/439&theme=dark">
    <source media="(prefers-color-scheme: light)" srcset="https://badge.race-of-sloths.com/FroVolod?type=bot&pr=near/near-cli-rs/439&theme=light">
    Shows profile picture for the author of the PR
</picture>](https://race-of-sloths.com/profile/FroVolod)


<details><summary>Current status: <i>waiting for scoring</i></summary>

We're waiting for maintainer to score this pull request with `@race-of-sloths score [0,1,2,3,5,8,13]` command. Alternatively, autoscoring [1,2] will be applied for this pull request

</details><details><summary>What is the Race of Sloths</summary>
<p>
Race of Sloths is a friendly competition where you can participate in challenges and compete with other open-source contributors within your normal workflow

For contributors:

- Tag @race-of-sloths inside your pull requests
- Wait for the maintainer to review and score your pull request
- Check out your position in the [Leaderboard](https://race-of-sloths.com/leaderboard)
- Keep weekly and monthly streaks to reach higher positions
- Boast your contributions with a dynamic picture of your [Profile](https://race-of-sloths.com/profile/FroVolod)

For maintainers:
- Score pull requests that participate in the Race of Sloths and receive a reward
- Engage contributors with fair scoring and fast responses so they keep their streaks
- Promote the Race to the point where the Race starts promoting you
- Grow the community of your contributors

Feel free to check [our website](https://race-of-sloths.com) for additional details!
</p>
</details> 

<details>
<summary>Bot commands</summary>

- For contributors
  - **Include a PR:** `@race-of-sloths include` to enter the Race with your PR
- For maintainers:
  - **Invite contributor** `@race-of-sloths invite` to invite the contributor to participate in a race or include it, if it's already a runner.
  - **Assign points:** `@race-of-sloths score [1/2/3/5/8/13]` to award points based on your assessment.
  - **Reject this PR:** `@race-of-sloths exclude` to send this PR back to the drawing board.
  - **Exclude repo:** `@race-of-sloths pause` to stop bot activity in this repo until `@race-of-sloths unpause` command is called

</details>

File: src/common.rs (hunk 1 above)
Comment (FroVolod) [reply src/common.rs]: Done

**Review by frol — APPROVED** [review]
