### PR TITLE
fix: Wrong console command for adding Function-Call key with unlimited allowance

### LINKED ISSUE #341: Required allowance for Function-Call Keys
Hi,

After this PR:

https://github.com/near/near-cli-rs/pull/330

`allowance` attribute became required, but the documentation states that this attribute is optional:

https://docs.near.org/concepts/protocol/access-keys#function-call-keys

```
allowance (Optional): The amount of NEAR allowed to be spent on gas. If omitted, the key can consume unlimited as gas
```

Which implementation is correct?

### PR DESCRIPTION
**Pull request by FroVolod**
Resolves #341 

_near-cli_ (JS) command with "allowance":
```
near add-key example-acct.testnet GkMNfc92fwM1AmwH1MTjF4b7UZuceamsq96XPkHsQ9vi --allowance 30000000000 --contract-id example-contract.testnet --method-names example_method
```
_near-cli-rs_ command:
```
near account add-key example-acct.testnet grant-function-call-access --allowance '30000000000 NEAR' --receiver-account-id example-contract.testnet --method-names example_method use-manually-provided-public-key GkMNfc92fwM1AmwH1MTjF4b7UZuceamsq96XPkHsQ9vi network-config testnet sign-with-keychain send
```

_near-cli_ (JS) command without "allowance":
```
near add-key example-acct.testnet GkMNfc92fwM1AmwH1MTjF4b7UZuceamsq96XPkHsQ9vi --contract-id example-contract.testnet --method-names example_method
```
_near-cli-rs_ command:
```
near account add-key example-acct.testnet grant-function-call-access --allowance unlimited --receiver-account-id example-contract.testnet --method-names example_method use-manually-provided-public-key ed25519:GkMNfc92fwM1AmwH1MTjF4b7UZuceamsq96XPkHsQ9vi network-config testnet
```

### CODE REVIEW

**Review by frol — CHANGES_REQUESTED** [review]

File: src/types/near_allowance.rs [hunk 1]
```diff
@@ -0,0 +1,91 @@
...
+        if let Some(amount) = self.0 {
+            amount.fmt(f)
+        } else {
+            write!(f, "{UNLIMITED}")
+        }
+    }
+}
+
+impl std::str::FromStr for NearAllowance {
+    type Err = color_eyre::eyre::Report;
```
Comment (frol) [inline src/types/near_allowance.rs:27]: Let's try using `near_token::NearTokenError` for consistency

```suggestion
    type Err = near_token::NearTokenError;
```

File: src/types/near_token.rs [hunk 2]
```diff
@@ -11,6 +11,7 @@ const ONE_NEAR: u128 = 10u128.pow(24);
     derive_more::From,
     derive_more::Into,
     derive_more::FromStr,
+    PartialEq,
```
Comment (frol) [inline src/types/near_token.rs:14]: Move it up (after `Copy`), and add `Eq`, `PartialOrd`, and `Ord` derives for completeness.

**Review by frol — CHANGES_REQUESTED** [review]

File: src/types/near_token.rs (hunk 2 above)
Comment (FroVolod) [reply src/types/near_token.rs]: Done

**Review by frol — APPROVED** [review]
